### ISSUE TITLE
Taking product offline or create new product with offline status, causes it not showing correctly in admin

### ISSUE THREAD

**Issue by osari** [firesale/firesale#128]
If I take a product status to 'Draft' from 'Online', or create a new product and set the status to 'Draft', it displays incorrectly in product admin, empty 'Product Code', 'Title', 'Parent Category', 'Stock Level', and 'Current Price'. Links to 'Quick Edit', 'Edit' and 'Delete' do not have the product id at the end of the URL. The data is updated/entered correctly to db.

**Comment by jHoldroyd** [comment]
This issue was fixed in [this](https://github.com/firesale/FireSale/commit/f48db655f67db107a23334600a00656b88759c66) commit and should be making it into the next 1.0.5 release in the next week or so if not 1.1, for now you can download the latest version from GitHub and it should be taken care of.

Thank you for the report though, forgot about this one still being live.
