### ISSUE TITLE
Checkout Total is $0.00

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#136]
I'm unable to check out if the total is $0.00.  Some of our members get items for free.  How can I allow them to check out with a $0.00 total so we can track that they are ordering an item?

**Comment by jHoldroyd** [comment]
This was a change that was somehow pushed out of the master branch but has been re-added for 1.1, however you can add it in yourself by going to controllers/front_cart.php and changing line 329 to:

```
if ( ! $this->fs_cart->total_items())
```

Basically checks if there's items in the cart rather than a cost, not quite sure how or why this disappeared but that's what needs changed anyways.
