### ISSUE TITLE
Error message with categories

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#137]
Hi,
there is a problem with the categories.
If you try to access via URL to a category that doesn't exists the system shows this error:

{"status":false,"message":"Found no files matching system\/cms\/modules\/pages\/css\/firesale.css","data":""}

It should redirect to a 404 or something else

**Comment by jHoldroyd** [comment]
Which version is this on, still the 1.0.4 branch?

**Comment by ChristianGiupponi** [comment]
Yes, 1.0.4.
Edit:
it's a new instalaltion

**Comment by jHoldroyd** [comment]
Ah, this is already fixed in the 1.1.0 branch, it just requires moving the css/js template settings into the index function when a category is valid, opposed to the constructor. You can see what the change here: https://github.com/firesale/FireSale/blob/1.1/develop/firesale/controllers/front_category.php#L141
