### ISSUE TITLE
Why are we using numbers for order statuses?

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#139]
Using numbers for order statuses makes adding new ones quite difficult without it looking silly.

We have:
1 : Unpaid
2 : Paid
3 : Dispatched
4 : Processing
5 : Refunded
6 : Cancelled

So if I wanted to add "Pending", it will have to be number 7, which is annoying because it should go after unpaid.

Can we use slugs for the order statuses? "unpaid", "paid", "dispatched" etc. Would make it not only easier to add new statuses, but it would make it easier to remember the key for the status without referring to the details.php file all the time.

**Comment by jHoldroyd** [comment]
Yeah, this is the plan in 1.2 with the big update to orders where we can not only have a default list and full order status updates but it'll have the same type of feature as attributes and even have custom order status' - still some stuff to figure out but it's all being done for 1.2 for sure.

**Comment by hsq** [comment]
There is one thing which can bite you.. When you want to show a list of statusses, the list will be alphabetical. A slug would be alright, but also use an index. In a multilingual environment, you might want to use codes... 
I usually have 2-3 languages.. Dutch, english, french. So it is needed...

**Comment by jHoldroyd** [comment]
The numbers aren't displayed anywhere and are just the reference the site uses behind the scenes, the only issue I think Chris has with this is that it makes it a little difficult sometimes to know what ID to set where. If they're ever displayed anywhere it's the title and not the value so I'm not sure it's an issue.

I'm quite partial to how it is now for a number of reasons and the main one is that every order would have a multi-character string rather than a single ID. So I'm kinda torn between ease of use and the extra storage requirements it brings.

We'll see how it goes though.

**Comment by jHoldroyd** [comment]
Closed as this has become a none issue with the intended plans for 1.3.0
