### ISSUE TITLE
Order Get Addresses 

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#141]
In the Get Addresses function when we want to retrieve all of the addresses so the user can pick one that they have used in the past.  Title isn't required in the form, but for it to be retrieved it needs to be.  This is not consistent.

``` php
    public function get_addresses($user)
    {

        // Set query paramaters
        $params  = array(
                    'stream'    => 'firesale_addresses',
                    'namespace' => 'firesale_addresses',
                    'where'     => "created_by = '{$user}' AND title != ''",
                    'order_by'  => 'id',
                    'sort'      => 'desc'
                   );

```

To?

``` php
    public function get_addresses($user)
    {

        // Set query paramaters
        $params  = array(
                    'stream'    => 'firesale_addresses',
                    'namespace' => 'firesale_addresses',
                    'where'     => "created_by = '{$user}'",
                    'order_by'  => 'id',
                    'sort'      => 'desc'
                   );

```

**Comment by jHoldroyd** [comment]
The reason it's like this is because storing an address for later use is an optional thing, a user may have 1 or 2 primary addresses they always use, but may want something shipped to a new address they're not that interested in having saved for reuse and so if they don't opt to save it, they don't see it again. To the system there's no difference, we save the address anyways because we have to, they'll just never see it again.

That's why it's like it is, if for your store want to make it show all addresses, you can simply make a change to details to require the title field and the lines posted above will make no difference because it'll always have be set.

We felt it was necessary to give people the choice to save an address for later use or not.
