### ISSUE TITLE
Checkout when shipping module is disabled.

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#167]
FireSale v 1.1 gives this error when "Submit & Pay" is pressed. Shipping module is disabled.

```
Error Number: 1054

Unknown column 'shipping' in 'field list'

INSERT INTO `default_firesale_orders` (`ship_to`, `bill_to`, `gateway`, `shipping`, `created_by`,    `order_status`, `price_sub`, `price_ship`, `price_total`, `ip`, `created`, `ordering_count`, `currency`, `exchange_rate`) VALUES ('3', '3', '7', 0, '1', '1', '', '0.00', '0.00', '127.0.0.1', '2012-11-01 22:44:00', 0, 1, '1')

Filename: /addons/shared_addons/modules/firesale/models/orders_m.php

Line Number: 185
```

**Comment by jHoldroyd** [comment]
I'll look into this, we've never had a problem with it before but I'll see if there's anything we can do

**Comment by from2day** [comment]
I have question about shipping module. While there is no forum and not finished documentation I will ask here :)

I've got above error while there was shipping module disabled. I do not need shipping at all. Do I need those ship_to and bill_to fields separately? I understad that checkbox "same address" is for that. I do modify my forms and streams accordingly for my needs but they does not work correctly 100% trough whole cart checkout process. 

In other hand, Firesale is module based. Considering that, shouldn't it be "friendly" when shipping module is disabled? What is your vision on e-shop with digital downloads, less filling forms, fast checkout?

**Comment by jHoldroyd** [comment]
In 1.1 you can set your products to not require shipping and all it will ask for is billing details and nothing more. It shouldn't be giving you any issues to not have the shipping module installed and is not something we've encountered before, but are looking into as it shouldn't happen.

FireSale is modular as you pointed out but only to a degree, come 1.2 we'll be splitting it up much further to allow for a wide range of new functions regardless of product type and is something we'll be discussing more in the next week or so.

**Comment by jHoldroyd** [comment]
Both myself and Chris have been through this a few times and cannot recreate it, the module has checks in place to ensure that the shipping module is or isn't installed and allows for the process to be done without it. During the whole time testing the checkout process both with and without the module this has never occurred and the only suggestion I have is to try a fresh install of 1.1 and see how you get on, or simply add the missing column back in to the database with the following command:

```
ALTER TABLE `default_firesale_orders` ADD `shipping` INT( 11 ) DEFAULT '0' NOT NULL ;
ALTER TABLE `default_firesale_orders` ADD INDEX ( `shipping` ) ;
```

The issue that was originally posted was due to a missing database entry that is added by default with or without the shipping module and is simply set to 0. Even when the shipping module is installed and uninstalled this column is added back in.

I'm going to close this now and if nothing suggested above helps I'll reopen it and go deeper into the issue.
