### ISSUE TITLE
FireSALE Front-end 

### ISSUE THREAD

**Issue by james182** [firesale/firesale#18]
How is the front-end navigation supposed to work, to access the store front ?

my process: PyroCMS > design > navigation > add link > store

the link is then firesale_search, correct?

Result: Page Missing

**Comment by jHoldroyd** [comment]
We're taking care of this very soon, but the best way to add search for instance to the menu is if you add a URI instead of a module, so you just need to put in search and it'll be there. At the moment though the search page is blank without terms and is what we intend to address over the weekend as well as the default views which have been missing until now.
