### ISSUE TITLE
Space as Thousand Separator Symbol [request]

### ISSUE THREAD

**Issue by FornetMK** [firesale/firesale#239]
The system does not accept space as thousand separator symbol at the moment. 

In Polish - we  use "," (coma) as decimal symbol and with thousands separator -  we do not use any additional symbols. Numbers under 10000 are rather written together. Only big numbers - use space like 1 000 000. But at the moment in FireSale you cannot define nor space nor no-symbol.

**Comment by jHoldroyd** [comment]
Ok so there was no real way around this one other than to (on post) convert the space to its' html entity alternative, since streams or ci trims all post data it's seen as a blank field if we didn't intervene before it was checked. This is in the 1.2.0/develop branch and  should look fine when displayed.
