### ISSUE TITLE
1.2/develop - PyroPro multisite manager

### ISSUE THREAD

**Issue by osari** [firesale/firesale#256]
Upon uploading all modules on PyroPro, going to Add-Ons of the domain produces error:

An Error Was Encountered
Unable to load the requested class: firesale

However, when logging in from the domain's admin section and going to Add-ons, the above error does not appear and installation went smoothly.

**Comment by jHoldroyd** [comment]
This bug happens when Firesale is in place before an install is done. Pyro runs a check on the addons that are installed and firesale requires a library that pyro can't see at that point and this error occurs. 

We are aware of it and there's a few possible fixes but for the time being you can just add firesale to the addons folder after the install is complete.

**Comment by jHoldroyd** [comment]
I've moved this to 1.3 because without a total rewrite (which will happen in 1.3 anyways) we can't fix this problem easily.

**Comment by jHoldroyd** [comment]
I'll wait for Chris to confirm but I'm pretty sure this has been taken care of now
