### ISSUE TITLE
1.2/dev - install errors

### ISSUE THREAD

**Issue by FornetMK** [firesale/firesale#257]
I am trying to install 1.2 devel ver of FireSale on clear and fresh installation of PyroCMS Pro. 
(1.2 downoladed 20 minutes ago)

Cannot install it - because getting all the time streams [emtpy field] error. Updating the installation from working 1.1 master to 1.2 devel (by replacing module files) gives the same error.

Any hints what to check and test?

**Comment by jHoldroyd** [comment]
What version of Pyro was this done on? I've just run 5 clean and 5 upgrade installs on both 2.1.3 and 2.2.0-dev and had no issues with any of them.

Edit: It's also possible that this error is being caused by installing in Polish (I presume) and there still being strings missing for certain fields. If you could give it a try again in English and see how that goes and I'll do a diff in a few moments to make sure everything is in the correct place for all languages.

**Comment by jHoldroyd** [comment]
Ok after doing a check and updating the language files if you weren't installing in English that's the cause of this problem. The Polish translations (as well as the others actually) hadn't been updated with the latest strings required for installation and that will have caused the streams errors you experienced.

If you pull down the latest copy you should find everything working as it should in any language again, apologies for that but we leave the language diffs until we're done with a patch generally.

**Comment by FornetMK** [comment]
Yes, English language instalation works fine. 
Thanks for the solution :)
