### ISSUE TITLE
Brands Design issue in Admin panel

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#273]
When you click on the "Brands" label the view display everityng eccept the other label to change section su as "Producs, categories etc"

[Image](http://awesomescreenshot.com/06fuqgcbf)

**Comment by jHoldroyd** [comment]
That's because we're currently stripping out all of the hacks we put in place to merge all modules into one list as we can just add them to the dropdown now without any merging like we had to do in the past. This should be fixed when this process is done but I'll leave it open and assign it to Chris until then.

**Comment by jHoldroyd** [comment]
The changes are now pretty much done, but this is how things are going to be from now on. The dropdown menu will hold all of the menus and the sub-menu under the header will contain the module specific links. This is to avoid the issue of running out of space and as all aspects are available under the header it seems like the only way to do it.

I'm closing this now as we don't really see another way to do it. We may come back to it but as space is limited with just a few modules installed but for now that's how it's staying.
