### ISSUE TITLE
Error on install of firesale_shipping

### ISSUE THREAD

**Issue by johnwarlick** [firesale/firesale#302]
I downloaded the 2.2 compatible module from the addon store and when I go to install it on Version 2.2.0 Professional (/admin/addons/modules/install/firesale_shipping) I get this: 

An Error Was Encountered [ 500 ]

field_slug_in_use [add_field]

Am I doing something wrong or is this a bug?

**Comment by jHoldroyd** [comment]
Nothing changed in the install process between 1.1 and 1.2 for shipping. Was this a clean install or was it an upgrade?

**Comment by johnwarlick** [comment]
It was a clean install, sorry for not responding sooner

**Comment by jHoldroyd** [comment]
I'm not entirely sure how on a clean install you can get the field slug in use issues, I would presume you've hit an issue with installation and tried to install over the top of it again rather than uninstalling and installing fresh. I'll close this now as we've had no other reported instances of it but if you can try that suggestion and report back that'd be great.
