### ISSUE TITLE
Two products with the same slugs are possible

### ISSUE THREAD

**Issue by jurajdurajka** [firesale/firesale#320]
FireSale v1.2.1 (base, without any additional modules)

It is possible to create two products with the same slug, in which case only the most recently added product is shown in the shop and can be routed to.

I don't know if this is a bug or a feature, but it is a little bit confusing.

**Comment by jurajdurajka** [comment]
Thanks for the quick fix! I have a question: if I select a product in Products admin, click "duplicate and then Save it, this will still allow me to add products with the same slug. Is this behavior correct?

**Comment by jHoldroyd** [comment]
Either something went wrong with the update and your slug hasn't been set to unique or it's not working as it should be. Duplicate doesn't use streams and as such doesn't pay attention to the unique field with is a streams thing and not a database requirement. The reason I've left it this way is because the latest version simply renames the duplicated product and the slug so it won't match the existing one anymore (whereas it used to keep them identical).

**Comment by jurajdurajka** [comment]
allright - I just merged this specific bugfix into my project. Therefore I understand that in the complete latest version it should not be a problem anymore. thanks a lot!
