### ISSUE TITLE
Gateway updates

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#331]
Firstly gateways should have images attached to them,  we should allow users to add/edit the images of gateway choices as well as adding defaults for our currently supported ones out of the box.

Secondly we should add a gateway plugin to list out the currently enabled ones with information and images.

**Comment by chrisnharvey** [comment]
I can get this feature in tonight if you like.

Sent from my iPhone

On 18 Apr 2013, at 09:20 AM, Jamie Holdroyd notifications@github.com
wrote:

Firstly gateways should have images attached to them, we should allow users
to add/edit the images of gateway choices as well as adding defaults for
our currently supported ones out of the box.

Secondly we should add a gateway plugin to list out the currently enabled
ones with information and images.

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/firesale/issues/331
.

**Comment by jHoldroyd** [comment]
Sounds good, would be nice to have it in the theme to make it dynamic

**Comment by chrisnharvey** [comment]
I've added a plugin method to list the currently enabled gateways. As for the image uploads, I have decided not to include this as it is more of a designers job rather than an admins job. The admin panel is designed for clients really.

Although you could have the gateway images in the theme, then run a loop with Lex on the enabled gateways and display the images accordingly.
