### ISSUE TITLE
Shipping price doesn't work

### ISSUE THREAD

**Issue by joserico** [firesale/firesale#364]
front_cart.php line 337 always insert into order shipping price 0,00
this code fix it

// Shipping option
//if ( $data['ship_req'] AND isset($this->firesale->roles['shipping']) AND isset($input['shipping'])) {
                if ( $data['ship_req'] AND isset($input['shipping'])) {
                    //$role = $this->firesale->roles['shipping'];
                    //$shipping = $this->$role['model']->get_option_by_id($input['shipping']);
                    $shipping = $this->shipping_m->get_option_by_id($input['shipping']);
                } else {
                    $shipping['price'] = '0.00';
                }

**Comment by joserico** [comment]
And other small bug when send  data to Paypal. The name appear like 0.

libraries/mechant_paypal_express.php
changes on line 103
//$request[$prefix.'SHIPTONAME'] = $this->param('name');
$request[$prefix.'SHIPTONAME'] = $this->param('first_name').' '.$this->param('last_name');

**Comment by jHoldroyd** [comment]
About the shipping price, I'm not sure which version you're using but that looks like it was from a long while ago as shipping hasn't worked like that since pre-1.2.0. If you get the latest version of 1.2/develop that should be taken care of.

As for the merchant names I'll pass this onto Chris to look into and see what he wants to do with it.

**Comment by joserico** [comment]
Ok :) and thanks for your great work

**Comment by jHoldroyd** [comment]
No problem, closing this now but I'll still get Chris to look into the label issues in PayPal for you.
