### ISSUE TITLE
Internet Explorer bugs?

### ISSUE THREAD

**Issue by treerunner** [firesale/firesale#370]
I've got a client that is experiencing bugginess on our dev install with category management and image uploads - this is using IE 10. 

Category bug might possibly be user error - I need to watch them and/or test on a windows machine.

Image uploads is definitely not working for them. Is there a fallback for "browser does not support HTML 5 file uploads" ?

Does FS support Internet Explorer? thanks in advance..

**Comment by jHoldroyd** [comment]
Seems the library we're using for uploads has been abandoned by the author so we found a fixed version that didn't work and instead fixed it up ourselves. Everything seems to be working great again, it does have a file field fallback but it thinks the browser supports it but due to a bug in the library it wasn't so it was never shown.

**Comment by treerunner** [comment]
THANKS!
