### ISSUE TITLE
Error when changing Variant title 

### ISSUE THREAD

**Issue by alexborton** [firesale/firesale#380]
When changing the a variant title from it's original through the modifiers tab, upon saving the title fancybox overlay loads in the main CMS page with an error and notification. 

Error reads: That Product can not be found
Notifications reads: Variation edited successfully

Once the window is closed and the page reloaded, the variation is updated. 

Thanks

![screen-grab](https://f.cloud.github.com/assets/1439507/708626/9b830dde-de4b-11e2-8f2c-e68e365f7482.jpg)

**Comment by pavoltanuska** [comment]
There is also an error when deleting variation.

It doesn't close the overlay just loads product create form to it.

Cause of this error:
- in https://github.com/firesale/firesale/blob/1.2/develop/firesale/views/admin/products/create.php on line 100 there is a link to variation edit form. Instead of:
  `{{ url:site }}admin/firesale/products/variation/<?php echo $id; ?>/<?php echo $variation['id']; ?>`
  it should be
  `{{ url:site }}admin/firesale/products/variation/<?php echo $modifier['id']; ?>/<?php echo $variation['id']; ?>`
