### ISSUE TITLE
Install failure with Pyro 2.1.5 and FireSale 1.2.1

### ISSUE THREAD

**Issue by ikoniqoz** [firesale/firesale#387]
Here is what I have just experienced. I have a fresh install of PyroCMSPro 2.1.5  AND FireSale 1.2.1. The install of FireSale appears to go OK - All the module's folders were included in the install however, I dont get anything in the Pyro CP for Firesale. If I navigate to mysite.dev/admin/firesale I get an SQL error. 

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders`' at line 2

SELECT SUM(i.`qty`) AS `count`, SUM(i.`qty` \* i.`price`) AS `sales`, date_format(i.`created`, `"%Y-%m")` AS `month` FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders` AS o ON `o`.`id` = `i`.`order_id` WHERE `o`.`order_status` IN (2, 3, 4) AND date_format(i.`created`, "%Y-%m") > '2012-07-14' GROUP BY `month` ORDER BY `month` asc LIMIT 12

I have gone thru the process 4 or 5 times and on each occassion I get the same result. 

UPDATE: Installed FireSale 1.1.0 with PyroCMSPro 2.1.5 and it appears to have installed correctly. Looks like a hard error with the Install process for 1.2.1.

**Comment by jHoldroyd** [comment]
Pyro 2.1.x has been considered legacy since the launch of 2.2 and as such we no longer test our releases against it. If you would like to use any of our 1.2.x (and beyond) releases you will need to upgrade, it may be possible to fox them but its not something we have the time to do unfortunately.

**Comment by ikoniqoz** [comment]
OK - I understand. Unfortunately PyroCMS 2.2.1 is unfit for production purposes. As a result I have reverted back to 2.1.5 for this project. I have four 2.2.1 projects underway and I regret starting with that version. I most certainly cant use it for this project that requires FireSale.
How would I upgrade from FireSale 1.1 to 1.2 on PyroCMS 2.1.5?

**Comment by jHoldroyd** [comment]
There's a few different things you could try, the good news about that error is that it is only on the dashboard and for the most part the rest of the system should be pretty functional. The bad news is that we've had that error reported to us once before and were never able to replicate it to fix, I think we came to the conclusion it was something with an older version of MySQL but could never quite sort it out. If you do manage to find a fix for it we'd be more than happy to include it.

The menu system may be the other issue but I'm not entirely sure how it works on that front since we've not touched 2.1.5 in many months now.

**Comment by ikoniqoz** [comment]
Thanks Jamie. Since I am not a CI developer I dont hold out much hope of solving these issues.
