### ISSUE TITLE
Another problem with categories

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#46]
It seems that the cateogry problem has not been fixed because if i click on a category it doesn't show the "Edit" or "Delete" button but it shows the "Add new category"

**Comment by jHoldroyd** [comment]
Can I just ask what are the details of the category that is causing the problem? Might just be a JS issue with some of the details of a particular category.

**Comment by from2day** [comment]
ChristianGiupponi, does your categories titles have non english characters?

Category items with non English characters ž, ę, ū gives:

Error: The server is not responding correctly, please try again later.

I think data must be encoded during Ajax transfer.

**Comment by ChristianGiupponi** [comment]
no no i use standard character in my test.
I haven't try whit à or è that in italian are frequent! As soos as possibile i will try!

**Comment by jHoldroyd** [comment]
I'll go through that now and see if I can find a fix, I was sure it was done with the last update but I'll see if I missed something for you. Can I ask, which category is causing the issue or is it all of them (id preferably)?

**Comment by from2day** [comment]
It intrigues me that not all of them are giving that error.
Category name "Kita" with link 
www.my-domain.lt/admin/firesale/categories/ajax_cat_details/15?csrf_hash_name=9387ee8ebbbfab0c0f069b1dda572f17
gives false.

Category is not seen on front side category list.

**Comment by from2day** [comment]
There is something with category status field in DB. I haven't figured it out why, but some of the entries had status = 0, after manual change to 1 works fine.

**Comment by jHoldroyd** [comment]
I'm not quite sure what to say, I'm testing everything I can think of and even the use of as many special characters I can find in the title and cannot replicate any of the above issues with the categories. I'll keep going but without any errors or line numbers to look at I don't know what to tell you guys.

Here's a screenshot of the latest version with special characters etc. http://d.pr/i/Tts7

Just as a note, accessing the ajax_cat_details function directly will output nothing because it checks if you're accessing it via ajax or not.

**Comment by from2day** [comment]
Try setting category status to 0 and you will get the error :)
I don't know when and why it had been changed in some categories. 

All characters works well - Great!

For now I think the case is closed.

**Comment by jHoldroyd** [comment]
That should be taken care of, thanks for the extra info :)
