### ISSUE TITLE
Long list of errors on orders page when a user is deleted

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#51]
When a user is deleted, the orders page in the backend shows a long list of errors when trying to access the user object.

**Comment by jHoldroyd** [comment]
Should be fixed now.

**Comment by chrisnharvey** [comment]
Still getting this issue. Reopening.

**Comment by jHoldroyd** [comment]
Filed a pull request for the 2.2 develop branch of Pyro to take care of this issue. It's not specifically anything to do with FireSale but is caused by the streams_core user field type and should hopefully be accepted.

It can be viewed here: https://github.com/pyrocms/pyrocms/pull/1862

Closing this now
