### ISSUE TITLE
Enhancement - Product list, add to cart

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#96]
When a user is in the products list in the frontend (category/category-slug) can easy add the product to the cart.
The problem is that every time that you click on "Add to basket" the site redirect you to the cart but maybe the user want to continue to shop.

Why don't use ajax to add the product to the cart and allow user to continue their shopping?

What do you think?

**Comment by chrisnharvey** [comment]
Nice idea, I've assigned this to Jamie so he can look into it.

**Comment by jHoldroyd** [comment]
This is really for theme developers to decide I think. In our original demo theme we did exactly this and it worked very well (if you check the cart code, we do respond with json to ajax requests) so the code is there, the issue comes down to what should be default to the views and what shouldn't.

I fully agree anyone developing a real website should do this as it adds a huge extra level of convenience to the process of buying, but out of the box the default views (in my mind) are nothing more than a way to debug as you develop a real theme for your store. I'd hate to imagine anyone running a store from our default views, and while they work well, they're not intended for this purpose.

We have the code and I may add it at some point but we can't with the default views show you a small version of the cart so giving visual feedback that it's done and that it's gone into the cart (short of using alerts) is a no go.

**Comment by ChristianGiupponi** [comment]
Ok, I understan your point of view.
A goodidea could be the possibility to add this features via CP, assume that a person which have no html and css skills want to use this module and want to use the dafault theme of Pyro...Why don't give the possibility to activate the ajax functionalities?

It's just a supposition :)

**Comment by jHoldroyd** [comment]
Like I said I'll consider it, I think the default views have a long way to go still (they were kinda thrown together) but they are rather limited by the default view we're kinda "forced" to work within. We could build a partially functional shopping cart overview with the DOM and inject it into the header, but it'll disappear whenever you're on a non-firesale page. We'll look at the options available though and figure something out that works.

**Comment by ChristianGiupponi** [comment]
ok, I understand :)
If you want you can close this :)

**Comment by jHoldroyd** [comment]
It's all about feedback to the user, there's possibly a few things we could work with, it's not a huge priority right now, but I will leave this open and return to it at some point in the near future with a compromise that should work.

We're just planning out the next few big updates at the moment for 1.1, 1.2 and 1.3 and trying to slot new features, updates and cleanups, so I'll try and get this and a few other views improvements in there somewhere,

**Comment by jHoldroyd** [comment]
I'm going to close this now, we've made another one of our little decisions and we're going to clean up the existing theme we have and release it along with the core, for free. So we'll be moving our default views over to that in a minor version in the next few weeks. We felt this was the best way to demonstrate the power of FireSale and just how dynamic it can be by fitting into a proper theme instead of (badly) integrating into the default pyro theme.
